In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[ 'the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',]
      

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7972, 9852, 8960, 2862],
 [7972, 9852, 8960, 2691],
 [7972, 6137, 8960, 109],
 [7826, 8040, 1834, 3683, 102],
 [7826, 8040, 1834, 3683, 1612],
 [5305, 7972, 8454, 8960, 363],
 [2991, 6239, 3245, 3683]]

In [8]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7972 9852 8960 2862]
 [   0    0    0    0 7972 9852 8960 2691]
 [   0    0    0    0 7972 6137 8960  109]
 [   0    0    0 7826 8040 1834 3683  102]
 [   0    0    0 7826 8040 1834 3683 1612]
 [   0    0    0 5305 7972 8454 8960  363]
 [   0    0    0    0 2991 6239 3245 3683]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 197ms/step


array([[[ 0.01912123, -0.0248908 , -0.01556337, -0.03921199,
         -0.0041484 , -0.0420627 , -0.01222567,  0.04807713,
          0.04074898,  0.01694288],
        [ 0.01912123, -0.0248908 , -0.01556337, -0.03921199,
         -0.0041484 , -0.0420627 , -0.01222567,  0.04807713,
          0.04074898,  0.01694288],
        [ 0.01912123, -0.0248908 , -0.01556337, -0.03921199,
         -0.0041484 , -0.0420627 , -0.01222567,  0.04807713,
          0.04074898,  0.01694288],
        [ 0.01912123, -0.0248908 , -0.01556337, -0.03921199,
         -0.0041484 , -0.0420627 , -0.01222567,  0.04807713,
          0.04074898,  0.01694288],
        [-0.00268358,  0.00232625,  0.04914354,  0.03360509,
          0.0144364 ,  0.04625918, -0.03456134, -0.0173225 ,
          0.00164681,  0.0005474 ],
        [ 0.00160277,  0.03941857,  0.03899646, -0.01431812,
         -0.02422957, -0.0429542 , -0.02658185, -0.02305081,
          0.02280133,  0.02591199],
        [-0.04915347, -0.00599758,  0.04782145,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 7972, 9852, 8960, 2862])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 34ms/step


array([[ 0.01912123, -0.0248908 , -0.01556337, -0.03921199, -0.0041484 ,
        -0.0420627 , -0.01222567,  0.04807713,  0.04074898,  0.01694288],
       [ 0.01912123, -0.0248908 , -0.01556337, -0.03921199, -0.0041484 ,
        -0.0420627 , -0.01222567,  0.04807713,  0.04074898,  0.01694288],
       [ 0.01912123, -0.0248908 , -0.01556337, -0.03921199, -0.0041484 ,
        -0.0420627 , -0.01222567,  0.04807713,  0.04074898,  0.01694288],
       [ 0.01912123, -0.0248908 , -0.01556337, -0.03921199, -0.0041484 ,
        -0.0420627 , -0.01222567,  0.04807713,  0.04074898,  0.01694288],
       [-0.00268358,  0.00232625,  0.04914354,  0.03360509,  0.0144364 ,
         0.04625918, -0.03456134, -0.0173225 ,  0.00164681,  0.0005474 ],
       [ 0.00160277,  0.03941857,  0.03899646, -0.01431812, -0.02422957,
        -0.0429542 , -0.02658185, -0.02305081,  0.02280133,  0.02591199],
       [-0.04915347, -0.00599758,  0.04782145,  0.00418027, -0.02308862,
         0.00115286,  0.03685868, -0.03942728